name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install g++ make libnetfilter-conntrack-dev -y
    - name: Build
      run: make
    - name: Run
      run: ./iptstate --version
